# Generated by Django 5.2.17 on 2026-09-29 02:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayAuditLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(default='INBOUND', max_length=16)),
                ('endpoint', models.CharField(default='/api/v2/regulatory/gateway', max_length=255)),
                ('status_code', models.IntegerField(default=200)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GatewayScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SUCCESS', 'All Returns Validated & Accepted (200 OK)'), ('VALIDATION_ERROR', 'NBE Rejection - Cross-Item Validation Mismatch (422)'), ('AUTH_FAILURE', 'NBE BSD Portal Rejected - mTLS / Certificate Expired (401)'), ('TIMEOUT', 'NBE BSD Gateway Timeout (504)'), ('SERVER_ERROR', 'NBE Core Banking Ingestion Error (500)'), ('RANDOM_FLAKY', 'Intermittent Flaky Network Mode (Simulate Retries)')], default='SUCCESS', max_length=32)),
                ('latency_ms', models.IntegerField(default=50)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('flaky_failure_rate', models.FloatField(default=0.4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gateway Scenario',
            },
        ),
        migrations.CreateModel(
            name='NbeSubmissionRecord',
            fields=[
                ('submission_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('report_key', models.CharField(db_index=True, max_length=64)),
                ('institution_code', models.CharField(default='0000013', max_length=32)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(default='ACCEPTED', max_length=32)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
