# Generated by Django 5.2.17 on 2026-09-29 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_id', models.CharField(max_length=64)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_role', models.CharField(max_length=32)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('details', models.TextField()),
                ('old_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=32)),
                ('persisted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Compliance Audit Log',
                'verbose_name_plural': 'Compliance Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
