# Generated by Django 5.2.17 on 2026-09-29 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvidence',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('submission_id', models.CharField(db_index=True, max_length=64)),
                ('report_key', models.CharField(max_length=64)),
                ('finding_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('tamper_seal', models.CharField(blank=True, max_length=128)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified Integrity'), ('PENDING_REVIEW', 'Pending Review'), ('FLAGGED', 'Flagged / Tampered')], default='VERIFIED', max_length=32)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Audit Evidence',
                'verbose_name_plural': 'Audit Evidence Records',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('submission_id', models.CharField(db_index=True, max_length=64)),
                ('report_key', models.CharField(db_index=True, max_length=64)),
                ('department', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical Regulatory Non-Compliance'), ('HIGH', 'High Risk Material Discrepancy'), ('MEDIUM', 'Medium Variance / Policy Exception'), ('LOW', 'Low Severity Data Documentation Issue'), ('INFORMATIONAL', 'Informational / Process Improvement')], default='MEDIUM', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('REMEDIATION_PENDING', 'Remediation Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ACCEPTED_RISK', 'Accepted Risk')], default='OPEN', max_length=32)),
                ('regulatory_reference', models.CharField(blank=True, max_length=255)),
                ('affected_field', models.CharField(blank=True, max_length=128)),
                ('financial_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('auditor_id', models.CharField(max_length=64)),
                ('auditor_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Finding',
                'verbose_name_plural': 'Audit Findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReportPackage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=64)),
                ('scope_departments', models.JSONField(default=list)),
                ('generated_by', models.CharField(max_length=255)),
                ('findings_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('executive_summary', models.TextField()),
                ('tamper_seal', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Report Package',
                'verbose_name_plural': 'Audit Report Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditWorkingNote',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('submission_id', models.CharField(db_index=True, max_length=64)),
                ('report_key', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('OBSERVATION', 'Audit Observation'), ('METHODOLOGY', 'Testing Methodology'), ('RISK_NOTE', 'Risk Note'), ('INQUIRY', 'Management Inquiry')], default='OBSERVATION', max_length=32)),
                ('author_id', models.CharField(max_length=64)),
                ('author_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Working Note',
                'verbose_name_plural': 'Audit Working Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('finding_id', models.CharField(db_index=True, max_length=64)),
                ('action_plan', models.TextField()),
                ('assigned_department', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed by Department'), ('OVERDUE', 'Overdue'), ('VERIFIED_BY_AUDITOR', 'Verified by Auditor')], default='PENDING', max_length=32)),
                ('remediation_proof', models.TextField(blank=True)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Remediation Action',
                'verbose_name_plural': 'Remediation Actions',
                'ordering': ['target_date'],
            },
        ),
    ]
