# Generated by Django 5.2.17 on 2026-09-29 02:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=16)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Registration Verification'), ('PASSWORD_RESET', 'Password Reset Verification')], default='REGISTRATION', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Compliance Administrator'), ('MAKER', 'Regulatory Reporting Maker'), ('CHECKER', 'Four-Eyes Regulatory Checker'), ('AUDITOR', 'Internal Compliance Auditor')], default='MAKER', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Account'), ('PENDING_APPROVAL', 'Pending Compliance Approval'), ('DISABLED', 'Disabled Account')], default='ACTIVE', max_length=32)),
                ('institution_code', models.CharField(default='0000013', max_length=32)),
                ('department', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=64, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FINGERPRINT', 'Touch ID / Fingerprint Sensor'), ('FACE', 'Face ID / Facial Recognition Sensor')], max_length=32)),
                ('credential_id', models.CharField(db_index=True, max_length=255)),
                ('device_label', models.CharField(blank=True, max_length=255)),
                ('face_hash', models.TextField(blank=True)),
                ('public_key', models.TextField(blank=True)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'type', 'credential_id')},
            },
        ),
    ]
