# Generated by Django 5.2.17 on 2026-09-29 02:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorRequestLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('method', models.CharField(default='POST', max_length=16)),
                ('path', models.CharField(max_length=256)),
                ('status_code', models.IntegerField(default=200)),
                ('status_text', models.CharField(default='200 OK', max_length=64)),
                ('return_key', models.CharField(blank=True, default='', max_length=64)),
                ('institution_code', models.CharField(blank=True, default='0000013', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('tls_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Simulator API Log',
                'verbose_name_plural': 'Simulator API Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ALWAYS_SUCCESS', 'Always Success (200 OK + Cryptographic Receipt)'), ('VALIDATION_ERROR', 'Validation Error (422 Unprocessable Entity)'), ('AUTH_FAILURE', 'Mutual TLS / Auth Failure (401 Unauthorized)'), ('TIMEOUT', 'Gateway Timeout (504 Gateway Timeout)'), ('SERVER_ERROR', 'Central Bank Server Error (500 Internal Server Error)'), ('RANDOM_FLAKY', 'Random Flaky (Intermittent Network / Server Errors)')], default='ALWAYS_SUCCESS', max_length=32)),
                ('latency_ms', models.IntegerField(default=150, help_text='Configured delay in milliseconds before responding')),
                ('flaky_failure_rate', models.FloatField(default=0.3, help_text='Failure probability for RANDOM_FLAKY mode')),
                ('failure_message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulator Scenario',
                'verbose_name_plural': 'Simulator Scenarios',
            },
        ),
        migrations.CreateModel(
            name='SimulatorSubmission',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('report_key', models.CharField(db_index=True, max_length=64)),
                ('institution_code', models.CharField(default='0000013', max_length=32)),
                ('fin_year', models.IntegerField(default=2026)),
                ('period_start', models.CharField(blank=True, default='', max_length=32)),
                ('period_end', models.CharField(blank=True, default='', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(default='ACCEPTED', max_length=32)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Received Submission',
                'verbose_name_plural': 'Received Submissions',
                'ordering': ['-received_at'],
            },
        ),
    ]
